--------------------------------------------------------
--  파일이 생성됨 - 목요일-11월-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POST_COMMENT
--------------------------------------------------------

  CREATE TABLE "C##BLUE"."POST_COMMENT" 
   (	"COMMENT_ID" NUMBER(*,0), 
	"POST_ID" NUMBER(*,0), 
	"USER_ID" VARCHAR2(500 BYTE), 
	"COMMENT_DATE" TIMESTAMP (6), 
	"IS_COMMENT_MODIFIED" NUMBER(*,0), 
	"COMMENT_CONTENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "C##BLUE"."POST_COMMENT"  IS '댓글';
REM INSERTING into C##BLUE.POST_COMMENT
SET DEFINE OFF;
Insert into C##BLUE.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,COMMENT_DATE,IS_COMMENT_MODIFIED,COMMENT_CONTENT) values (1,1234,'qwer',to_timestamp('24/11/15 19:23:07.956771000','RR/MM/DD HH24:MI:SSXFF'),213,'뭘봐');
Insert into C##BLUE.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,COMMENT_DATE,IS_COMMENT_MODIFIED,COMMENT_CONTENT) values (2,1234,'asdf',to_timestamp('24/11/18 13:40:08.707280000','RR/MM/DD HH24:MI:SSXFF'),865,'나가라');
Insert into C##BLUE.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,COMMENT_DATE,IS_COMMENT_MODIFIED,COMMENT_CONTENT) values (3,1234,'asdf',to_timestamp('24/11/20 13:34:43.353859000','RR/MM/DD HH24:MI:SSXFF'),1234,'아니');
Insert into C##BLUE.POST_COMMENT (COMMENT_ID,POST_ID,USER_ID,COMMENT_DATE,IS_COMMENT_MODIFIED,COMMENT_CONTENT) values (4,1234,'asdf',to_timestamp('24/11/20 13:35:11.933806000','RR/MM/DD HH24:MI:SSXFF'),53,'응');
--------------------------------------------------------
--  DDL for Index PK_BLOG_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BLUE"."PK_BLOG_COMMENT" ON "C##BLUE"."POST_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOG_COMMENT_INDEX_2
--------------------------------------------------------

  CREATE INDEX "C##BLUE"."BLOG_COMMENT_INDEX_2" ON "C##BLUE"."POST_COMMENT" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOG_COMMENT_INDEX_3
--------------------------------------------------------

  CREATE INDEX "C##BLUE"."BLOG_COMMENT_INDEX_3" ON "C##BLUE"."POST_COMMENT" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_POST_COMMENT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##BLUE"."TRG_POST_COMMENT_ID" 
BEFORE INSERT ON post_comment
FOR EACH ROW
BEGIN
  -- 새로운 행이 삽입될 때 comment_id에 시퀀스 값 할당
  :NEW.comment_id := post_comment_seq.NEXTVAL;
END;

/
ALTER TRIGGER "C##BLUE"."TRG_POST_COMMENT_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("COMMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("IS_COMMENT_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."POST_COMMENT" ADD CONSTRAINT "PK_BLOG_COMMENT" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##BLUE"."POST_COMMENT" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table POST_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##BLUE"."POST_COMMENT" ADD CONSTRAINT "FK_POST_COMMENT_POST_ID_SITE_POST_POST_ID" FOREIGN KEY ("POST_ID")
	  REFERENCES "C##BLUE"."SITE_POST" ("POST_ID") ENABLE;
