--------------------------------------------------------
--  파일이 생성됨 - 목요일-11월-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SITE_POST
--------------------------------------------------------

  CREATE TABLE "C##BLUE"."SITE_POST" 
   (	"POST_ID" NUMBER(*,0), 
	"POST_TITLE" VARCHAR2(500 BYTE), 
	"IS_POST_MODIFIED" NUMBER(*,0) DEFAULT 0, 
	"AUTHOR_ID" NUMBER(*,0), 
	"DATE_PUBLISHED" TIMESTAMP (6), 
	"VIEWS" NUMBER(*,0) DEFAULT 0, 
	"USER_ID" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(500 BYTE) DEFAULT '정보게시판', 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"POST_ARTICLE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "C##BLUE"."SITE_POST"  IS '게시글';
REM INSERTING into C##BLUE.SITE_POST
SET DEFINE OFF;
Insert into C##BLUE.SITE_POST (POST_ID,POST_TITLE,IS_POST_MODIFIED,AUTHOR_ID,DATE_PUBLISHED,VIEWS,USER_ID,CATEGORY,MODIFIED_DATE,POST_ARTICLE) values (1234,'qqqq',1123,12343,to_timestamp('24/11/18 19:04:55.220761000','RR/MM/DD HH24:MI:SSXFF'),47,'qwer','정보게시팜',to_timestamp('24/11/19 13:33:19.074844000','RR/MM/DD HH24:MI:SSXFF'),'안녕');
Insert into C##BLUE.SITE_POST (POST_ID,POST_TITLE,IS_POST_MODIFIED,AUTHOR_ID,DATE_PUBLISHED,VIEWS,USER_ID,CATEGORY,MODIFIED_DATE,POST_ARTICLE) values (2,'asa',12,1223,to_timestamp('24/11/18 13:39:38.379118000','RR/MM/DD HH24:MI:SSXFF'),1,'asdf','정보안팜',to_timestamp('24/11/12 13:33:22.273673000','RR/MM/DD HH24:MI:SSXFF'),'하니');
Insert into C##BLUE.SITE_POST (POST_ID,POST_TITLE,IS_POST_MODIFIED,AUTHOR_ID,DATE_PUBLISHED,VIEWS,USER_ID,CATEGORY,MODIFIED_DATE,POST_ARTICLE) values (15,'ㅎㄺㅇㄷㄴ',0,1,to_timestamp('24/11/21 19:19:01.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'1','ㅎㅅㄱㄷㅇㄴ',null,'ㅎㄱㄷㅇㄴ');
--------------------------------------------------------
--  DDL for Index PK_BLOG_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BLUE"."PK_BLOG_POST" ON "C##BLUE"."SITE_POST" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOG_POST_INDEX_2
--------------------------------------------------------

  CREATE INDEX "C##BLUE"."BLOG_POST_INDEX_2" ON "C##BLUE"."SITE_POST" ("AUTHOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOG_POST_INDEX_3
--------------------------------------------------------

  CREATE INDEX "C##BLUE"."BLOG_POST_INDEX_3" ON "C##BLUE"."SITE_POST" ("IS_POST_MODIFIED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SITE_POST
--------------------------------------------------------

  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("POST_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("IS_POST_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("DATE_PUBLISHED" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("VIEWS" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."SITE_POST" ADD CONSTRAINT "PK_BLOG_POST" PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SITE_POST
--------------------------------------------------------

  ALTER TABLE "C##BLUE"."SITE_POST" ADD CONSTRAINT "FK_SITE_POST_USER_ID_USER_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##BLUE"."USER" ("USER_ID") ENABLE;
