--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ¸ñ¿äÀÏ-11¿ù-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

  CREATE TABLE "C##BLUE"."USER" 
   (	"USER_ID" VARCHAR2(500 BYTE), 
	"EMAIL" VARCHAR2(500 BYTE), 
	"PASSWORD" VARCHAR2(500 BYTE), 
	"NICKNAME" VARCHAR2(500 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE, 
	"DELETE_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "C##BLUE"."USER"  IS 'È¸¿ø';
REM INSERTING into C##BLUE."USER"
SET DEFINE OFF;
Insert into C##BLUE."USER" (USER_ID,EMAIL,PASSWORD,NICKNAME,ROLE,CREATED_DATE,DELETE_DATE,UPDATE_DATE) values ('qwer','qwer','1234','¸¶¸¾','qwer',to_date('24/11/16','RR/MM/DD'),to_date('24/11/17','RR/MM/DD'),to_date('24/11/18','RR/MM/DD'));
Insert into C##BLUE."USER" (USER_ID,EMAIL,PASSWORD,NICKNAME,ROLE,CREATED_DATE,DELETE_DATE,UPDATE_DATE) values ('asdf','asdf','2345','ÇªÇª','asdf',to_date('24/11/18','RR/MM/DD'),to_date('24/11/18','RR/MM/DD'),to_date('24/11/18','RR/MM/DD'));
Insert into C##BLUE."USER" (USER_ID,EMAIL,PASSWORD,NICKNAME,ROLE,CREATED_DATE,DELETE_DATE,UPDATE_DATE) values ('1','jjjj','mnbv','¤µ¤µ¤µ','USER',to_date('24/11/21','RR/MM/DD'),null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008340
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BLUE"."SYS_C008340" ON "C##BLUE"."USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER
--------------------------------------------------------

  ALTER TABLE "C##BLUE"."USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##BLUE"."USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
